#!/bin/bash
# Cloudflare DNS Setup Script for Fataplus Web Backend

set -e

echo "🌐 Cloudflare DNS Setup for Fataplus Web Backend"
echo "=============================================="

# Configuration
DOMAIN="fata.plus"
API_SUBDOMAIN="api"
STAGING_SUBDOMAIN="staging-api"
PLATFORM_SUBDOMAIN="platform"

echo "🔧 Required Actions in Cloudflare Dashboard:"
echo "=========================================="
echo ""

echo "1. Log in to Cloudflare Dashboard:"
echo "   https://dash.cloudflare.com"
echo ""

echo "2. Add your domain: $DOMAIN"
echo "   - Click 'Add site'"
echo "   - Enter: $DOMAIN"
echo "   - Choose Free plan"
echo "   - Continue and update nameservers"
echo ""

echo "3. Update Nameservers at your domain registrar:"
echo "   ns1.cloudflare.com"
echo "   ns2.cloudflare.com"
echo ""

echo "4. Add DNS Records in Cloudflare DNS section:"
echo "   ==================================="
echo ""
echo "   A Records:"
echo "   ----------"
echo "   Type: A"
echo "   Name: $API_SUBDOMAIN"
echo "   IPv4 address: 192.168.1.1 (temporary - will update after deployment)"
echo "   Proxy status: Proxied (orange cloud)"
echo "   TTL: Auto"
echo ""
echo "   Type: A"
echo "   Name: $STAGING_SUBDOMAIN"
echo "   IPv4 address: 192.168.1.1 (temporary - will update after deployment)"
echo "   Proxy status: Proxied (orange cloud)"
echo "   TTL: Auto"
echo ""
echo "   Type: A"
echo "   Name: $PLATFORM_SUBDOMAIN"
echo "   IPv4 address: 192.168.1.1 (temporary - will update after deployment)"
echo "   Proxy status: Proxied (orange cloud)"
echo "   TTL: Auto"
echo ""

echo "   CNAME Records (after Workers deployment):"
echo "   --------------------------------------"
echo "   Type: CNAME"
echo "   Name: $API_SUBDOMAIN"
echo "   Target: your-workers-subdomain.workers.dev"
echo "   Proxy status: Proxied (orange cloud)"
echo "   TTL: Auto"
echo ""
echo "   Type: CNAME"
echo "   Name: $STAGING_SUBDOMAIN"
echo "   Target: your-staging-workers-subdomain.workers.dev"
echo "   Proxy status: Proxied (orange cloud)"
echo "   TTL: Auto"
echo ""

echo "5. SSL/TLS Configuration:"
echo "   ======================="
echo "   - Go to SSL/TLS → Overview"
echo "   - Set encryption mode to 'Full (strict)'"
echo "   - Enable Always Use HTTPS"
echo ""

echo "6. Workers Configuration:"
echo "   ======================"
echo "   - Go to Workers & Pages"
echo "   - Create service: fataplus-web-backend"
echo "   - Upload code from cloudflare-deploy/ directory"
echo "   - Add custom domain: api.fata.plus"
echo "   - Add route: api.fata.plus/*"
echo ""

echo "7. Environment Variables (in Workers Settings):"
echo "   ==========================================="
echo "   - ENVIRONMENT: production"
echo "   - PLATFORM_URL: https://platform.fata.plus"
echo "   - MOTIA_SERVICE_URL: https://ai-service.fata.plus"
echo ""

echo "📋 DNS Record Summary:"
echo "====================="
echo ""
echo "| Host | Type | Value | Proxy |"
echo "|------|------|-------|-------|"
echo "| api | A | 192.168.1.1 | Proxied |"
echo "| staging-api | A | 192.168.1.1 | Proxied |"
echo "| platform | A | 192.168.1.1 | Proxied |"
echo "| www | CNAME | platform.fata.plus | Proxied |"
echo ""

echo "⏱️  Timeline:"
echo "============="
echo "- DNS propagation: 24-48 hours"
echo "- SSL certificate: 1-24 hours"
echo "- Workers deployment: 5-10 minutes"
echo ""

echo "🔍 Verification Commands:"
echo "======================="
echo "# Check DNS propagation:"
echo "nslookup api.fata.plus"
echo "nslookup staging-api.fata.plus"
echo ""
echo "# Check SSL certificate:"
echo "openssl s_client -connect api.fata.plus:443"
echo ""
echo "# Test API endpoints:"
echo "curl https://api.fata.plus/health"
echo "curl https://api.fata.plus/"
echo "curl https://api.fata.plus/security/health"
echo ""

echo "🎯 Next Steps:"
echo "==============="
echo "1. Complete Cloudflare setup (steps above)"
echo "2. Deploy Workers application"
echo "3. Update DNS records with Workers URLs"
echo "4. Test deployment"
echo "5. Monitor health and performance"
echo ""

echo "📞 Support:"
echo "==========="
echo "- Cloudflare Dashboard: https://dash.cloudflare.com"
echo "- Workers Documentation: https://developers.cloudflare.com/workers"
echo "- DNS Status: https://www.whatsmydns.net/"
echo ""

echo "✅ DNS setup guide created!"
echo "🚀 Proceed with Cloudflare dashboard setup..."