#!/bin/bash

echo "🔑 Récupération du Token Cloudflare"
echo "=================================="
echo ""
echo "Vous vous êtes connecté à Cloudflare, parfait ! 🎉"
echo ""
echo "Pour synchroniser la connexion avec cet environnement sandbox,"
echo "nous avons besoin de votre token d'API Cloudflare complet."
echo ""
echo "📋 Étapes pour récupérer votre token :"
echo ""
echo "1. 🌐 Allez sur : https://dash.cloudflare.com/profile/api-tokens"
echo ""
echo "2. 🔍 Recherchez un token existant nommé 'Wrangler' ou 'Workers'"
echo "   OU"
echo "   ➕ Cliquez sur 'Créer un token'"
echo ""
echo "3. ⚙️  Si vous créez un nouveau token, utilisez le modèle :"
echo "   📦 'Edit Cloudflare Workers' template"
echo "   OU configurez les permissions :"
echo "   - Zone:Zone:Read"
echo "   - Zone:DNS:Edit"  
echo "   - Account:Cloudflare Workers:Edit"
echo "   - Account:Pages:Edit"
echo "   - Account:D1:Edit"
echo "   - Account:R2:Edit"
echo ""
echo "4. 📝 Copiez le TOKEN COMPLET (40+ caractères)"
echo ""
echo "5. 🚀 Exécutez : ./setup-cloudflare-manual.sh \"VOTRE-TOKEN-COMPLET\""
echo ""
echo "📊 Informations actuelles :"
echo "- Token partiel trouvé : 0769d254d9faa2f596648c4ecb87c048c1a86 (34 caractères - incomplet)"
echo "- Token requis : 40+ caractères"
echo "- Statut : ❌ Non authentifié"
echo ""
echo "💡 Une fois le token configuré, nous pourrons :"
echo "✓ Vérifier la connexion"
echo "✓ Lister vos ressources Cloudflare"
echo "✓ Déployer votre application"
echo ""
echo "❓ Besoin d'aide ? Consultez : cloudflare-token-guide.md"