#!/bin/bash

echo "🔑 Configuration Rapide Token Cloudflare"
echo "========================================"
echo ""
echo "📋 ÉTAPES À SUIVRE SUR CLOUDFLARE :"
echo ""
echo "1. 🌐 Aller sur : https://dash.cloudflare.com/profile/api-tokens"
echo ""
echo "2. ➕ Cliquer sur 'Create Token'"
echo ""
echo "3. 🎯 CHOISIR : 'Edit Cloudflare Workers' (RECOMMANDÉ)"
echo "   OU"
echo "   🔧 'Get started' pour Custom token"
echo ""
echo "4. ✅ VÉRIFIER que ces permissions sont incluses :"
echo ""
echo "   📊 Account permissions :"
echo "   ✓ Cloudflare Workers:Edit"
echo "   ✓ Account Settings:Read"
echo "   ✓ Page:Edit"
echo "   ✓ D1:Edit"
echo "   ✓ R2:Edit"
echo ""
echo "   🌐 Zone permissions :"
echo "   ✓ Zone:Read"
echo "   ✓ DNS:Edit"
echo ""
echo "5. ⏰ DURÉE : Choisir '1 year' ou 'Never expires'"
echo ""
echo "6. 🎯 Account resources : 'Include - All accounts'"
echo "   (ou sélectionner votre compte spécifique)"
echo ""
echo "7. 🌍 Zone resources : 'Include - All zones'"
echo "   (ou sélectionner votre domaine spécifique)"
echo ""
echo "8. 🎉 Cliquer 'Continue to summary' puis 'Create Token'"
echo ""
echo "9. 📝 COPIER le token complet (40+ caractères)"
echo ""
echo "10. 🚀 Revenir ici et exécuter :"
echo "    ./setup-cloudflare-manual.sh \"VOTRE-TOKEN-COMPLET\""
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "💡 CONSEIL : Le template 'Edit Cloudflare Workers' inclut"
echo "   automatiquement TOUTES les permissions nécessaires !"
echo ""
echo "❓ Besoin d'aide ? Consultez : cloudflare-token-permissions-guide.md"