version: '3.8'

services:
  web-backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://fataplus:password@postgres:5432/fataplus_prod
      - REDIS_URL=redis://redis:6379/0
      - JWT_SECRET_KEY=your-super-secret-jwt-key-here
      - MOTIA_SERVICE_URL=http://motia-service:8001
    depends_on:
      - postgres
      - redis
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - fataplus-network

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: fataplus_prod
      POSTGRES_USER: fataplus
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - fataplus-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - fataplus-network

volumes:
  postgres_data:
  redis_data:

networks:
  fataplus-network:
    driver: bridge
