apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-backend-deployment
  namespace: fataplus-staging
  labels:
    app: web-backend
    tier: backend
    environment: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-backend
      tier: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: web-backend
        tier: backend
        environment: staging
    spec:
      containers:
      - name: web-backend
        image: fataplus/web-backend:staging-latest
        ports:
        - containerPort: 8000
          name: http
        envFrom:
        - configMapRef:
            name: fataplus-config
        - secretRef:
            name: fataplus-secrets
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: logs
        emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-backend-deployment
  namespace: fataplus-production
  labels:
    app: web-backend
    tier: backend
    environment: production
spec:
  replicas: 4  # Higher availability for production
  selector:
    matchLabels:
      app: web-backend
      tier: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: web-backend
        tier: backend
        environment: production
    spec:
      containers:
      - name: web-backend
        image: fataplus/web-backend:production-latest
        ports:
        - containerPort: 8000
          name: http
        envFrom:
        - configMapRef:
            name: fataplus-config
        - secretRef:
            name: fataplus-secrets
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: logs
        emptyDir: {}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - web-backend
              topologyKey: kubernetes.io/hostname