# Cloudflare Workers configuration for Fataplus MCP Server
name = "fataplus-mcp-server"
main = "src/worker.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Account configuration
account_id = "f30dd0d409679ae65e841302cc0caa8c"

# Variables d'environnement
[vars]
ENVIRONMENT = "production"
LOG_LEVEL = "info"
CORS_ORIGINS = "https://fataplus.com,https://app.fataplus.com"

# D1 Database bindings (utilisant la base existante)
[[d1_databases]]
binding = "DB"
database_name = "fataplus-app"
database_id = "51ccc3a9-b4ca-4250-812d-65c9eebc4111"

# KV namespace bindings (utilisant les namespaces existants)
[[kv_namespaces]]
binding = "CACHE"
id = "5411019ff86f410a98f4616ce775d081"

[[kv_namespaces]]
binding = "MCP_DATA"
id = "9ce26ca5fe4c446d8146cfa213f9775f"

# Analytics engine bindings
[[analytics_engine_datasets]]
binding = "ANALYTICS"

# AI bindings for MCP AI processing
[ai]
binding = "AI"

# Environment-specific configurations
[env.staging]
name = "fataplus-mcp-staging"

[env.staging.vars]
ENVIRONMENT = "staging"
LOG_LEVEL = "debug"
CORS_ORIGINS = "https://staging.fataplus.com,https://*.pages.dev"

# Staging bindings
[[env.staging.d1_databases]]
binding = "DB"
database_name = "fataplus-app"
database_id = "51ccc3a9-b4ca-4250-812d-65c9eebc4111"

[[env.staging.kv_namespaces]]
binding = "CACHE"
id = "5411019ff86f410a98f4616ce775d081"

[[env.staging.kv_namespaces]]
binding = "MCP_DATA"
id = "9ce26ca5fe4c446d8146cfa213f9775f"

[[env.staging.analytics_engine_datasets]]
binding = "ANALYTICS"

[env.staging.ai]
binding = "AI"

# Observability
[observability]
enabled = true
# AutoRAG Configuration pour MCP
[[vectorize]]
binding = "VECTORIZE"
index_name = "fataplus-knowledge-base"
