version: '3.8'

services:
  # Main Fataplus Platform (matching Cloudron deployment)
  fataplus-local:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: fataplus-local
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    depends_on:
      - redis
      - postgres
    networks:
      - fataplus-network
    restart: unless-stopped

  # Redis (matching Cloudron Redis addon)
  redis:
    image: redis:7-alpine
    container_name: fataplus-redis-local
    command: redis-server --appendonly yes --requirepass fataplus123
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - fataplus-network
    restart: unless-stopped

  # PostgreSQL with PostGIS (matching Cloudron PostgreSQL addon)
  postgres:
    image: postgis/postgis:15-3.4
    container_name: fataplus-postgres-local
    environment:
      POSTGRES_DB: fataplus
      POSTGRES_USER: fataplus
      POSTGRES_PASSWORD: fataplus123
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fataplus -d fataplus"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - fataplus-network
    restart: unless-stopped

  # MinIO Object Storage (matching Cloudron object storage)
  minio:
    image: minio/minio:latest
    container_name: fataplus-minio-local
    environment:
      MINIO_ROOT_USER: fataplus
      MINIO_ROOT_PASSWORD: fataplus123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - fataplus-network
    restart: unless-stopped

volumes:
  redis_data:
  postgres_data:
  minio_data:

networks:
  fataplus-network:
    driver: bridge